class CanvasWindow extends Window {
	var tex;
	function CanvasWindow(width,height) {
		super.Window();
		setInnerSize( width, height );

		tex = new Texture( "bg01.jpg" );
		canvas.clearColor = 0xff0000ff;
	}
	function onDraw() {
		canvas.drawTexture( tex, 0, 0 );
	}
	// function onTouchDown(x, y, cx, cy, id) {}
}

//var win = new CanvasWindow(System.desktopWidth,System.desktopHeight);
var win = new CanvasWindow(640,480);
win.visible = true;

